a = input('Digite algo: ')
print('O tipo primitivo de desse valor é', type(a))
print('É alpha numérico?', a.isalnum())
print('Só tem espaços?', a.isspace())
print('É numérico?', a.isnumeric())
print('É alfabético?', a.isalpha())
print('É maiúsculo?', a.isupper())
print('É minúsculo?', a.islower())
print('É captalizado?', a.istitle())